// code generated by AI
#include "flowfield_detail.hpp"

#include <xatlas.h>

#include <cassert>
#include <cstdint>
#include <iostream>
#include <vector>

namespace flowfield::detail {

  static bool meshHasCompleteTexcoords(const ObjPolys& m) {
    if (m.nVT_in <= 0) return false;
    for (const auto& poly : m.polys) {
      for (const auto& idx : poly) {
        if (idx.texcoord_index < 0 || idx.texcoord_index >= m.nVT_in) return false;
      }
    }
    return true;
  }

  static bool generateUvWithXAtlas(const ObjPolys& inMesh, ObjPolys& outMesh) {
    const std::vector<Tri> tris = triangulate(inMesh);
    if (tris.empty()) {
      std::cerr << "xatlas UV gen: no triangles\n";
      return false;
    }

    const int nV = inMesh.nV_in;
    if (nV <= 0) return false;

    xatlas::Atlas* atlas = xatlas::Create();
    if (!atlas) return false;

    std::vector<uint32_t> indices;
    indices.reserve(tris.size() * 3);

    for (const Tri& t : tris) {
      const int a = t.v0(), b = t.v1(), c = t.v2();
      if (a < 0 || b < 0 || c < 0 || a >= nV || b >= nV || c >= nV) continue;
      indices.push_back((uint32_t)a);
      indices.push_back((uint32_t)b);
      indices.push_back((uint32_t)c);
    }

    xatlas::MeshDecl decl{};
    decl.vertexCount = (uint32_t)nV;
    decl.vertexPositionData = inMesh.attrib.vertices.data();
    decl.vertexPositionStride = sizeof(tinyobj::real_t) * 3;
    decl.indexCount = (uint32_t)indices.size();
    decl.indexData = indices.data();
    decl.indexFormat = xatlas::IndexFormat::UInt32;

    xatlas::AddMeshError err = xatlas::AddMesh(atlas, decl, 1);
    if (err != xatlas::AddMeshError::Success) {
      std::cerr << "xatlas::AddMesh failed: " << (int)err << "\n";
      xatlas::Destroy(atlas);
      return false;
    }

    xatlas::ChartOptions chartOpts{};
    xatlas::PackOptions packOpts{};
    packOpts.padding = 2;
    packOpts.resolution = 1024;
    packOpts.bilinear = true;

    xatlas::Generate(atlas, chartOpts, packOpts);

    if (atlas->meshCount < 1) {
      std::cerr << "xatlas generate produced no meshes\n";
      xatlas::Destroy(atlas);
      return false;
    }

    const xatlas::Mesh& xm = atlas->meshes[0];

    outMesh = ObjPolys{};
    outMesh.attrib.vertices.clear();
    outMesh.attrib.texcoords.clear();
    outMesh.polys.clear();

    outMesh.attrib.vertices.reserve((size_t)xm.vertexCount * 3);
    outMesh.attrib.texcoords.reserve((size_t)xm.vertexCount * 2);

    for (uint32_t vi = 0; vi < xm.vertexCount; ++vi) {
      const xatlas::Vertex& xv = xm.vertexArray[vi];
      const uint32_t src = xv.xref;

      if (src >= (uint32_t)nV) {
        outMesh.attrib.vertices.push_back(0);
        outMesh.attrib.vertices.push_back(0);
        outMesh.attrib.vertices.push_back(0);
      } else {
        const size_t base = (size_t)src * 3;
        outMesh.attrib.vertices.push_back(inMesh.attrib.vertices[base + 0]);
        outMesh.attrib.vertices.push_back(inMesh.attrib.vertices[base + 1]);
        outMesh.attrib.vertices.push_back(inMesh.attrib.vertices[base + 2]);
      }

      outMesh.attrib.texcoords.push_back((tinyobj::real_t)xv.uv[0]);
      outMesh.attrib.texcoords.push_back((tinyobj::real_t)xv.uv[1]);
    }

    outMesh.nV_in = (int)xm.vertexCount;
    outMesh.nVT_in = (int)xm.vertexCount;

    const uint32_t* outIdx = xm.indexArray;
    const uint32_t outIndexCount = xm.indexCount;

    outMesh.polys.reserve(outIndexCount / 3);
    for (uint32_t i = 0; i + 2 < outIndexCount; i += 3) {
      const uint32_t a = outIdx[i + 0];
      const uint32_t b = outIdx[i + 1];
      const uint32_t c = outIdx[i + 2];
      if (a >= xm.vertexCount || b >= xm.vertexCount || c >= xm.vertexCount) continue;

      std::vector<tinyobj::index_t> tri(3);
      tri[0].vertex_index = (int)a;
      tri[1].vertex_index = (int)b;
      tri[2].vertex_index = (int)c;

      // 1:1 mapping
      tri[0].texcoord_index = (int)a;
      tri[1].texcoord_index = (int)b;
      tri[2].texcoord_index = (int)c;

      tri[0].normal_index = -1;
      tri[1].normal_index = -1;
      tri[2].normal_index = -1;

      outMesh.polys.push_back(std::move(tri));
    }

    xatlas::Destroy(atlas);

    return meshHasCompleteTexcoords(outMesh);
  }

  bool ensureMeshHasUvs(ObjPolys& ioMesh) {
    if (meshHasCompleteTexcoords(ioMesh)) return true;

    ObjPolys uvMesh;
    if (!generateUvWithXAtlas(ioMesh, uvMesh)) return false;

    ioMesh = std::move(uvMesh);
    return true;
  }

} // namespace flowfield::detail
